# libsql
option(FUN_WITH_LIBSQL "Enable libsql (Turso) client support" OFF)
set(LIBSQL_INCLUDE_DIRS "")
set(LIBSQL_LINK_LIBS "")
if(FUN_WITH_LIBSQL)
  add_definitions(-DFUN_WITH_LIBSQL)
  find_package(PkgConfig QUIET)
  if(PKG_CONFIG_FOUND)
    pkg_check_modules(LIBSQL QUIET libsql)
    if(NOT LIBSQL_FOUND)
      pkg_check_modules(LIBSQL_CLIENT QUIET libsql-client)
      if(LIBSQL_CLIENT_FOUND)
        set(LIBSQL_FOUND TRUE)
        set(LIBSQL_INCLUDE_DIRS ${LIBSQL_CLIENT_INCLUDE_DIRS})
        set(LIBSQL_LINK_LIBS ${LIBSQL_CLIENT_LIBRARIES})
      endif()
    endif()
  endif()
  if(NOT LIBSQL_FOUND)
    find_library(LIBSQL_LIB sqlite3)
    if(LIBSQL_LIB)
      list(APPEND LIBSQL_LINK_LIBS ${LIBSQL_LIB})
    else()
      message(FATAL_ERROR "libsql not found. Install libsql (or compatible sqlite3 client) or disable FUN_WITH_LIBSQL.")
    endif()
  endif()
endif()
